//basic idea webpack
var $= require('jquery');

// var _= require('lodash');

var people = [{
  "id": 1,
  "first_name": "Olvan",
  "last_name": "Dawtre",
  "email": "odawtre0@simplemachines.org",
  "gender": "Male",
  "ip_address": "7.70.227.164"
}, {
  "id": 2,
  "first_name": "Sibyl",
  "last_name": "Mouat",
  "email": "smouat1@telegraph.co.uk",
  "gender": "Male",
  "ip_address": "150.56.234.233"
}, {
  "id": 3,
  "first_name": "Quentin",
  "last_name": "Buddell",
  "email": "qbuddell2@java.com",
  "gender": "Male",
  "ip_address": "49.217.192.121"
}, {
  "id": 4,
  "first_name": "Corey",
  "last_name": "Oulett",
  "email": "coulett3@unc.edu",
  "gender": "Male",
  "ip_address": "138.165.249.45"
}, {
  "id": 5,
  "first_name": "Cyrille",
  "last_name": "Schoenfisch",
  "email": "cschoenfisch4@stumbleupon.com",
  "gender": "Male",
  "ip_address": "248.124.63.79"
}, {
  "id": 6,
  "first_name": "Kennedy",
  "last_name": "Pattington",
  "email": "kpattington5@hud.gov",
  "gender": "Male",
  "ip_address": "181.57.67.131"
}, {
  "id": 7,
  "first_name": "Jeramey",
  "last_name": "Berthomieu",
  "email": "jberthomieu6@ameblo.jp",
  "gender": "Male",
  "ip_address": "229.125.68.112"
}, {
  "id": 8,
  "first_name": "Page",
  "last_name": "Bodle",
  "email": "pbodle7@msn.com",
  "gender": "Female",
  "ip_address": "0.233.69.201"
}, {
  "id": 9,
  "first_name": "Stillman",
  "last_name": "Fellis",
  "email": "sfellis8@tumblr.com",
  "gender": "Male",
  "ip_address": "33.215.142.181"
}, {
  "id": 10,
  "first_name": "Jeanna",
  "last_name": "Streather",
  "email": "jstreather9@meetup.com",
  "gender": "Female",
  "ip_address": "157.162.118.211"
}, {
  "id": 11,
  "first_name": "Teador",
  "last_name": "Heball",
  "email": "theballa@slideshare.net",
  "gender": "Male",
  "ip_address": "73.228.237.112"
}, {
  "id": 12,
  "first_name": "Fabio",
  "last_name": "MacMickan",
  "email": "fmacmickanb@phpbb.com",
  "gender": "Male",
  "ip_address": "0.156.119.35"
}, {
  "id": 13,
  "first_name": "Brady",
  "last_name": "Kyncl",
  "email": "bkynclc@nasa.gov",
  "gender": "Male",
  "ip_address": "60.243.124.123"
}, {
  "id": 14,
  "first_name": "Kerianne",
  "last_name": "Clears",
  "email": "kclearsd@hibu.com",
  "gender": "Female",
  "ip_address": "195.114.157.201"
}, {
  "id": 15,
  "first_name": "Biddy",
  "last_name": "Cullin",
  "email": "bculline@cnet.com",
  "gender": "Female",
  "ip_address": "138.127.195.233"
}, {
  "id": 16,
  "first_name": "Sunny",
  "last_name": "Whordley",
  "email": "swhordleyf@histats.com",
  "gender": "Male",
  "ip_address": "96.234.105.15"
}, {
  "id": 17,
  "first_name": "Caitlin",
  "last_name": "Howlings",
  "email": "chowlingsg@amazonaws.com",
  "gender": "Female",
  "ip_address": "151.66.101.194"
}, {
  "id": 18,
  "first_name": "Domingo",
  "last_name": "Hanton",
  "email": "dhantonh@over-blog.com",
  "gender": "Male",
  "ip_address": "171.72.84.107"
}, {
  "id": 19,
  "first_name": "Romeo",
  "last_name": "Wines",
  "email": "rwinesi@webnode.com",
  "gender": "Male",
  "ip_address": "11.120.147.143"
}, {
  "id": 20,
  "first_name": "Fanchon",
  "last_name": "Kobus",
  "email": "fkobusj@bravesites.com",
  "gender": "Female",
  "ip_address": "123.60.171.44"
}];

// var femaleCount = _.filter(people,{'gender': "Female"}).length;
// alert(femaleCount + "females");
for(var i =0;i<people.length;i++)
$('body').append("<h3>"+people[i].first_name+"</h3>");

console.log("Module1 Stuff");

